apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpd-pulseaudio-mqtt-ir.fullname" . }}
  labels:
    {{- include "mpd-pulseaudio-mqtt-ir.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mpd-pulseaudio-mqtt-ir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mpd-pulseaudio-mqtt-ir.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mpd-pulseaudio-mqtt-ir.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mqtt-ir-bridge
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/mpd-mqtt-ir-bridge.py"]
          env:
          - name: MPD_HOST
            value: "127.0.0.1"
          - name: MPD_PORT
            value: "6600"
          - name: VERBOSE
            value: "1"
          - name: POWERON_VOLUME
            value: {{ .Values.irbridge.poweron_volume | quote }}
          - name: MQTT_CONFIG
            value: {{ .Values.irbridge.mqtt_config | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: mpd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/mpd", "--no-daemon", "--stdout"]
          env:
          - name: PULSE_SERVER
            value: {{ .Values.mpd.pulse_server | quote }}
          - name: PULSE_SINK
            value: {{ .Values.mpd.pulse_sink | quote }}
          ports:
            - name: mpd
              containerPort: 6600
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mpd
          readinessProbe:
            tcpSocket:
              port: mpd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: music
              mountPath: "/var/lib/mpd/music"
              readOnly: true
      volumes:
        - name: music
{{- if .Values.mpd.persistentVolumeClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mpd.persistentVolumeClaimName | quote }}
{{- else }}
          emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
