apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpd-dlna-yamaha-avr.fullname" . }}
  labels:
    {{- include "mpd-dlna-yamaha-avr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mpd-dlna-yamaha-avr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mpd-dlna-yamaha-avr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      serviceAccountName: {{ include "mpd-dlna-yamaha-avr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

        {{- if or (eq .Values.variant "mpd-dlna-yamaha-avr") (eq .Values.variant "mpd-pulseaudio-mqtt-ir") }}
        - name: control--{{ include "mpd-dlna-yamaha-avr.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq .Values.variant "mpd-dlna-yamaha-avr" }}
          command: ["/usr/bin/mpd-dlna-yamaha-avr.py"]
          {{- end }}
          {{- if eq .Values.variant "mpd-pulseaudio-mqtt-ir" }}
          command: ["/usr/bin/mpd-mqtt-ir-bridge.py"]
          {{- end }}
          env:
          - name: VERBOSE
            value: "1"
          - name: MPD_HOST
            value: "127.0.0.1"
          - name: MPD_PORT
            value: "6600"
          {{- if eq .Values.variant "mpd-dlna-yamaha-avr" }}
          - name: MPD_STREAM_HOSTPORT
            value: "{{ .Values.service.streamhostExternal }}:{{ .Values.service.streamport }}"
          - name: YAMAHA_HOST
            value: {{ .Values.yamaha.host | quote }}
          - name: MAX_VOLUME_DB
            value: {{ .Values.yamaha.maxVolumeDb | quote }}
          - name: SURROUND_PROGRAM
            value: {{ .Values.yamaha.surroundProgram | quote }}
          {{- end }}
          {{- if eq .Values.variant "mpd-pulseaudio-mqtt-ir" }}
          - name: POWERON_VOLUME
            value: {{ .Values.irbridge.poweron_volume | quote }}
          - name: MQTT_CONFIG
            value: {{ .Values.irbridge.mqtt_config | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}

        {{- if eq .Values.variant "mpd-snapcast" }}
        - name: snapserver--{{ include "mpd-dlna-yamaha-avr.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/snapserver
            - --config=/dev/null
            - --server.datadir=/var/lib/snapserver
            - --stream.source=pipe:///var/lib/snapserver/snapfifo?name=default
            - --http.doc_root=/usr/share/snapserver/snapweb
          ports:
            - name: snap-stream
              containerPort: 1704
              protocol: TCP
            - name: snap-control
              containerPort: 1705
              protocol: TCP
            - name: snap-web
              containerPort: 1780
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/snapserver
              name: snapdata
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}

        - name: mpd--{{ include "mpd-dlna-yamaha-avr.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/mpd", "--no-daemon", "--stdout", "/etc/{{ .Values.variant }}.conf"]
          {{- if eq .Values.variant "mpd-pulseaudio-mqtt-ir" }}
          env:
          - name: PULSE_SERVER
            value: {{ .Values.mpd.pulse_server | quote }}
          - name: PULSE_SINK
            value: {{ .Values.mpd.pulse_sink | quote }}
          {{- end }}
          ports:
            - name: mpd
              containerPort: 6600
              protocol: TCP
          {{- if eq .Values.variant "mpd-dlna-yamaha-avr" }}
            - name: stream
              containerPort: 6601
              protocol: TCP
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: mpd
          readinessProbe:
            tcpSocket:
              port: mpd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: music
              mountPath: "/var/lib/mpd/music"
              readOnly: true
            {{- if eq .Values.variant "mpd-snapcast" }}
            - name: snapdata
              mountPath: /var/lib/snapserver
            {{- end }}

        {{- if .Values.mympd.enabled }}
        - name: mympd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mympd.image.repository }}:{{ .Values.mympd.image.tag }}"
          imagePullPolicy: {{ .Values.mympd.image.pullPolicy }}
          env:
          - name: MYMPD_SSL
            value: "false"
          - name: MPD_HOST
            value: "127.0.0.1"
          - name: MPD_PORT
            value: "6600"
          {{- range $key, $value := .Values.mympd.config }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: mympd
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mympd
          readinessProbe:
            tcpSocket:
              port: mympd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mympd-run
              mountPath: "/run/mpd"
            - name: mympd-workdir
              mountPath: /var/lib/mympd
            - name: mympd-cachedir
              mountPath: /var/cache/mympd
        {{- end }}

      volumes:
        - name: music
        {{- if .Values.mpd.persistentVolumeClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mpd.persistentVolumeClaimName | quote }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if eq .Values.variant "mpd-snapcast" }}
        - name: snapdata
          emptyDir:
            sizeLimit: 100Mi
        {{- end }}
        {{- if .Values.mympd.enabled }}
        - name: mympd-run
          emptyDir:
            sizeLimit: 100Mi
        - name: mympd-workdir
          emptyDir:
            sizeLimit: 100Mi
        - name: mympd-cachedir
          emptyDir:
            sizeLimit: 100Mi
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
