apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpd-dlna-yamaha-avr.fullname" . }}
  labels:
    {{- include "mpd-dlna-yamaha-avr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mpd-dlna-yamaha-avr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mpd-dlna-yamaha-avr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      serviceAccountName: {{ include "mpd-dlna-yamaha-avr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: snapserver--{{ include "mpd-dlna-yamaha-avr.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/snapserver
            - --config=/dev/null
            - --server.datadir=/var/lib/snapserver
            - --stream.source=pipe:///var/lib/snapserver/snapfifo?name=default
          ports:
            - name: snap-stream
              containerPort: 1704
              protocol: TCP
            - name: snap-control
              containerPort: 1705
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/snapserver
              name: snapdata
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: dlna-yamaha-avr--{{ include "mpd-dlna-yamaha-avr.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/mpd-control-bridge.py"]
          env:
          - name: MPD_HOST
            value: "127.0.0.1"
          - name: MPD_PORT
            value: "6600"
          - name: MPD_STREAM_HOSTPORT
            value: "{{ .Values.service.streamhostExternal }}:{{ .Values.service.streamport }}"
          - name: YAMAHA_HOST
            value: {{ .Values.yamaha.host | quote }}
          - name: VERBOSE
            value: "1"
          - name: MAX_VOLUME_DB
            value: {{ .Values.yamaha.maxVolumeDb | quote }}
          - name: SURROUND_PROGRAM
            value: {{ .Values.yamaha.surroundProgram | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: mpd--{{ include "mpd-dlna-yamaha-avr.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/mpd", "--no-daemon", "--stdout"]
          ports:
            - name: mpd
              containerPort: 6600
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mpd
          readinessProbe:
            tcpSocket:
              port: mpd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: music
              mountPath: "/var/lib/mpd/music"
              readOnly: true
            - name: snapdata
              mountPath: /var/lib/snapserver
      volumes:
        - name: snapdata
          emptyDir:
            sizeLimit: 1Gi
        - name: music
{{- if .Values.mpd.persistentVolumeClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mpd.persistentVolumeClaimName | quote }}
{{- else }}
          emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
