apiVersion: v1
kind: Service
metadata:
  name: {{ include "mpd-dlna-yamaha-avr.fullname" . }}
  labels:
    {{- include "mpd-dlna-yamaha-avr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mpd
      protocol: TCP
      name: mpd
    {{- if eq .Values.variant "mpd-dlna-yamaha-avr" }}
    - port: {{ .Values.service.streamport }}
      targetPort: stream
      protocol: TCP
      name: stream
    {{- end }}
    {{- if eq .Values.variant "mpd-snapcast" }}
    - port: {{ .Values.service.streamport }}
      targetPort: snap-stream
      protocol: TCP
      name: stream
    - port: {{ .Values.service.controlport }}
      targetPort: snap-control
      protocol: TCP
      name: control
    - port: {{ .Values.service.webport }}
      targetPort: snap-web
      protocol: TCP
      name: snapweb
    {{- end }}
  selector:
    {{- include "mpd-dlna-yamaha-avr.selectorLabels" . | nindent 4 }}
