{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mpd-pulseaudio-mqtt-ir.serviceAccountName" . }}
  labels:
    {{- include "mpd-pulseaudio-mqtt-ir.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
