apiVersion: v1
kind: Service
metadata:
  name: {{ include "mpd-pulseaudio-mqtt-ir.fullname" . }}
  labels:
    {{- include "mpd-pulseaudio-mqtt-ir.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mpd
      protocol: TCP
      name: mpd
  selector:
    {{- include "mpd-pulseaudio-mqtt-ir.selectorLabels" . | nindent 4 }}
